kind: OpenTelemetryCollector
apiVersion: opentelemetry.io/v1beta1
metadata:
 name: otel
 namespace: istio-system
spec:
 config:
   exporters:
     otlp:
       endpoint: tempo-tempo-mesh-gateway.tempo.svc.cluster.local:8090
       tls:
         insecure: false
         ca_file: "/var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt"
       auth:
         authenticator: bearertokenauth
       headers:
         X-Scope-OrgID: "prod"
   extensions:
     bearertokenauth:
       filename: "/var/run/secrets/kubernetes.io/serviceaccount/token"     
   receivers:
     otlp:
       protocols:
         grpc: {}
         http: {}
   service:
     extensions: [bearertokenauth]
     pipelines:
       traces:
         exporters:
           - otlp
         receivers:
           - otlp