apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: tempo-bucket-odf
  namespace: tempo
spec:
  generateBucketName: tempo-bucket-odf
  storageClassName: openshift-storage.noobaa.io